version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    container_name: portfolio-site
    ports:
      - '4040:4040'
    restart: always