name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract npm version
        id: extract_npm_version
        run: |
          VERSION=$(node -p -e "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and Push Docker image
        run: |
          REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          docker buildx build \
            --platform linux/arm64,linux/amd64 \
            -t ghcr.io/${REPO_NAME}:${{ env.VERSION }} \
            -t ghcr.io/${REPO_NAME}:latest \
            --push .

      - name: Output Docker image URL
        run: |
          REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          echo "Docker Image URL: ghcr.io/${REPO_NAME}:${{ env.VERSION }}"
          echo "Docker Image URL: ghcr.io/${REPO_NAME}:latest"
