name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract npm version
        id: extract_npm_version
        run: |
          VERSION=$(node -p -e "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker image with version tag
        run: |
          REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/${{ github.repository }}/$REPO_NAME:${{ env.VERSION }} .

      - name: Tag Docker image as latest
        run: |
          REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          docker tag ghcr.io/${{ github.repository }}/$REPO_NAME:${{ env.VERSION }} ghcr.io/${{ github.repository }}/$REPO_NAME:latest

      - name: Push Docker image with version tag
        run: |
          REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          docker push ghcr.io/${{ github.repository }}/$REPO_NAME:${{ env.VERSION }}

      - name: Push Docker image with latest tag
        run: |
          REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          docker push ghcr.io/${{ github.repository }}/$REPO_NAME:latest

      - name: Output Docker image URL
        run: |
          REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          echo "Docker Image URL: ghcr.io/${{ github.repository }}/$REPO_NAME:${{ env.VERSION }}"
          echo "Docker Image URL: ghcr.io/${{ github.repository }}/$REPO_NAME:latest"
